name: '🌈 surge.sh'
description: 'Publish build file to surge.sh'
branding:
  icon: 'cloud'
  color: 'green'
inputs:
  domain:
    description: 'surge.sh domain'
    required: true
  token:
    description: 'surge.sh token'
    required: true
  root:
    description: 'your build path'
    default: '.'
runs:
  using: 'node16'
  main: 'index.js'
