name: 'build-test'
on:
  # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - test
      - 'releases/*'

jobs:
  # make sure build/ci work properly
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run build

  # make sure the action works on a clean machine without building
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with: 
          domain: 'kwy-test.surge.sh'
          root: './public'
        env:
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}